version: '3.9'
services:
  nginx:
    image: cr.dev.saveonsp.com/gitweb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
      - "2222:22"
    volumes: 
      - ./keys:/mnt/keys
